### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by codeagencybe** [dunglas/frankenphp-wordpress#2]
Can't pull image due to error

` error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io`

MySQL image pulls just fine. 
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/7568546/201429931-27eec7f6-c2ef-4472-9819-94a928c8f983.png">

Also tried pull images like Caddy, Traefik, NGINX, all work fine. 
Only frankenphp-wordpress returns this error

**Comment by dunglas** [comment]
Can you try `docker pull dunglas/frnakenphp`?
